### ISSUE TITLE
can i help support kr translation?

### ISSUE THREAD

**Issue by alternative00** [Nawang17/client-momo#7]
can i help support kr translation for momosz?

**Comment by Nawang17** [comment]
Yes. That would be greatly appreciated.  I have integrated crowdin into this repository so u can easily contribute translations. 

You can go to this link [https://crowdin.com/project/momos](https://crowdin.com/project/momos) and start adding translations for korean (ko). Thank you again.

**Comment by alternative00** [comment]
thanks, done!

**Comment by Nawang17** [comment]
Thank you. I haven't added all the words yet but I will slowly add them and try to cover 100%.

**Comment by alternative00** [comment]
thanks!

**Comment by Nawang17** [comment]
I have now added like 90% of the words. Also I would like to acknowledge your contribution in the README file of this GitHub repository. If you have a preferred name or link you'd like me to include, let me know. I want to make sure you're properly credited for your work. Thank you again
